# Generated by Django 5.1.6 on 2025-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.CharField(max_length=20)),
                ("bus_capacity", models.PositiveIntegerField()),
                ("total_students", models.PositiveIntegerField()),
                ("total_stops", models.PositiveIntegerField()),
                ("total_distance_km", models.FloatField()),
                ("is_overloaded", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
